### ISSUE TITLE
Get Angular ref app(s) local

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ref-app-inspections#1]
## Task

1. **Priority 1:** Get at least the existing SPA ref app SVN'd in and successfully locally built. 
2. **Nice to have:** Get the current UI-less Work in Progress version locally running.

Details outlined below under **Directions**, courtesy of @atdiff.

### Checky

Once each UXer is successful, check your checky check thing below. This Issue would be closed once all are successful.

- [ ] @bignamehere 
- [x] @francisrupert

### Wiki
* https://wiki.tools.fsa.usda.gov/display/EAServices/Reference+App

### SVN
* **Angular 6/Webpack:** (in progress)
https://svn.itsd.fsa.usda.gov/svn/FSAREPO/AO/topsoil/spa-reference-app-ui/
* **AngularJS**
https://svn.itsd.fsa.usda.gov/svn/FSAREPO/AO/spa-reference/spa-reference-app-ui/branches/new-npm/

### Notes

> Depending on what node/npm version you’re running, you’ll get an error with `grunt serve` about “verbose” and it won’t let you serve. The easy way around this is to just use `--force`. For speed and simplicity, I typically end up running the app with...
```
grunt serve --skipTests=true --toConsole=true --force
```

> It’s best to use **npm** for installing in this particular case.  You could probably get yarn to work, but due to node-sass versions available in nexus, probably safest to go with npm.  I had to disconnect from nexus to get the better version of node-sass, so the package-lock.json file has reference to that.  So prepare to lose 15-30 minutes of your day, but it’ll save the headache of dealing with versions and such.

/c @arosenblum

**Comment by atdiff** [comment]
Depending on your npm version (2.x or 3+), the setup instructions will vary for the AngularJS version of the project.
For npm 2.x:
* Use https://svn.itsd.fsa.usda.gov/svn/FSAREPO/AO/spa-reference/spa-reference-app-ui/trunk/
* In package.json, remove fsa-gis
* Copy gis folder from https://svn.itsd.fsa.usda.gov/svn/FSAREPO/AO/spa-reference/spa-reference-app-ui/branches/new-npm/src/main/modules/ and add to project in src/main/modules
* Update app.js to import "./gis/gis"
* In inspection.js, update fsa.gis to be spa.gis
* Run npm install and wait
* NOTE: you may have to modify a couple of module versions in the package.json.

For npm 3 and higher:
- Use https://svn.itsd.fsa.usda.gov/svn/FSAREPO/AO/spa-reference/spa-reference-app-ui/branches/new-npm/

**Comment by bignamehere** [comment]
closing this as my environment does not seem to be compatible with the project dependencies.
