### ISSUE TITLE
Instantiate ref-app-inspections

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ref-app-inspections#2]
## Task
Stand up a basic Webpack tooling setup for our eventual design-focused prototype of a _New! and Improved! Inspections Reference App_.

## General Requirements
* Pretty much identical to https://github.com/USDA-FSA/fsa-style/issues/209 (maybe update this initial post with a more relevant version of that checklist).
* Consider what kind of _simple_ Webpack features would make prototyping more efficient? e.g. [include, and templating](https://angular.io/guide/template-syntax) 
  * Our intention isn't to go full-bore developer with this prototype, just make it simple and efficient to prototype. For example, no reason not to use jQuery if it gets it done quicker.
  * The investment in this task (and overall project) is easily worth it as it can serve as a good pilot for a would-be prototyping kit.

**Comment by bignamehere** [comment]
I was able to put together a Webpack only prototype kit that allows for basic inclusion of partials using inline interpolation. The prototype kit allows the Developer to `npm install fsa-style` and import an alias variable from the config file, which keeps FSA Style "black boxed" and separate from the project directories. [The `fsa-prototype-kit` repo is located here](https://github.com/USDA-FSA/fsa-prototype-kit).

I also tried to implement two different templating engines ([Nunjucks](https://mozilla.github.io/nunjucks/) & [Handlebars](http://handlebarsjs.com/)) to include more advanced expressions and data handling, but there isn't enough documentation online yet to clearly achieve what we are wanting for this project. A feature branch of Handlebars is working for the purpose of using HTML partials, but other advanced features are not working properly and should be explored if the project requires these features.

The above features most likely could be implemented using JavaScript and without a templating engine, but until this becomes a priority, we can hold off.
