### ISSUE TITLE
Inspecting a Farm: feature exploration/discovery

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ref-app-inspections#25]
### Action

Initially assigned to @arosenblum for at least screenshot collection. 

### Task

Collect features we'd like to showcase in the **Farm Details / Inspection Details / Edit Inspection / Create Inspection** portion of the SPA Reference App. This can be in any form (e.g. wish-lists, ideas, pie-in-sky tech features, screenshots of existing Farm Applications' equivalent).

### Desired Outcome

A healthy amount of inputs to inspire the UX team to design and prototype (at least) Inspection Details (#17).

### Background

[Enterprise Architecture Services > TERRA FIRMA: Target State Technical Architecture > Topsoil > SPA Framework > Reference App](https://wiki.tools.fsa.usda.gov/display/EAServices/Reference+App) 

The [previous SPA Ref App](https://sharepoint.fsa.usda.net/mgr/itsd/architecture/EA_Team/Shared%20Documents/ARCHITECTURE%20DOMAINS/XCut%20-%20UX/8.%20Projects/Reference%20Apps/Inspections/05%20deliverables/_published/SPA-Ref-App--Inspections-2015--High-Level-UI-Flow.v1.pdf) had a limited "Inspection Detail" view, screenshot below.

![image](https://user-images.githubusercontent.com/1165933/44528608-9a1ed680-a6af-11e8-9701-78b0f9d6ee50.png)

**Comment by arosenblum** [comment]
Here is the main window upon logging in as a Producer:
![farmplus - mainwindow](https://user-images.githubusercontent.com/10815406/44533497-42866800-a6bb-11e8-8d09-556261c0e88c.PNG)

**Comment by arosenblum** [comment]
When a farm is selected, the producer can navigate through different tabs of information.  Here are screenshots of each tab (at the bottom of the main screen):

**Summary tab:**
![farm - summary](https://user-images.githubusercontent.com/10815406/44533573-71044300-a6bb-11e8-963a-b68a55b72d7e.PNG)

**Land Use Tab**
![farm -landuse](https://user-images.githubusercontent.com/10815406/44533578-73ff3380-a6bb-11e8-87c6-1144102748ae.PNG)

**Base/Yield Tab**
![farm - baseyield](https://user-images.githubusercontent.com/10815406/44533585-782b5100-a6bb-11e8-920f-ca9cb0031f55.PNG)

**Elections Tab**
![farm - elections](https://user-images.githubusercontent.com/10815406/44533591-7b264180-a6bb-11e8-90e8-c040046b058e.PNG)

**Tracts Tab:**
![farm - tracts](https://user-images.githubusercontent.com/10815406/44533595-7eb9c880-a6bb-11e8-9840-8c61fc3eadb5.PNG)

**Comment by arosenblum** [comment]
From the Farm->Tracts tab, the Producer is presented with a list of Tracts.  When selecting a Tract, the following tabs display data about the selected tract:

**Tract Summary Tab**
![tract - summary](https://user-images.githubusercontent.com/10815406/44533722-cccecc00-a6bb-11e8-9e54-3cb28b982257.PNG)

**Tract Land Use Tab**
![tract - landuse](https://user-images.githubusercontent.com/10815406/44533760-dce6ab80-a6bb-11e8-838f-6f968aad3a3a.PNG)

**Tract Base/Yield Tab**
![tract - baseyield](https://user-images.githubusercontent.com/10815406/44533774-e3752300-a6bb-11e8-9995-c8c9fe3c18b0.PNG)

**Tract Producers Tab**
![tract - producers](https://user-images.githubusercontent.com/10815406/44533787-e96b0400-a6bb-11e8-9b49-1889730d46bf.PNG)

**Tract Fields Tab**
![tract - fields](https://user-images.githubusercontent.com/10815406/44533804-f0921200-a6bb-11e8-8251-a5fbfda6f1d1.PNG)

**Comment by arosenblum** [comment]
If a Producer then selects a Field from the Tract->Fields tab, the following tabs display:

**Field Summary Tab**
![field - summary](https://user-images.githubusercontent.com/10815406/44533870-0ef80d80-a6bc-11e8-9e13-71d5cf2a3975.PNG)

**Field CRP Tab**
![field - crp](https://user-images.githubusercontent.com/10815406/44533886-14edee80-a6bc-11e8-8f40-bb982da0cd4d.PNG)

**Comment by arosenblum** [comment]
@francisrupert @bignamehere Let me know if there is anything else you would like to see from Farm+.

**Comment by arosenblum** [comment]
The Land Use tab (at the Farm level) has 5 numbers that represent:
- WBP - Water Bank Program
- WRP - Wetland Reserve Program
- MPL - Marginal Pasture Land
- CRP - Conservation Reserve Program
- GRP - Grassland Reserve Program

These are decent candidates to add to an "Inspection".  An inspector could enter a value (decimal) for each representing the number of acres verified for each program.  Maybe each program (enrollment) is also verified (checkboxed) first?
