### ISSUE TITLE
Determine Inspections fake IA

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ref-app-inspections#6]
Currently...

`| Inspections | Reports🔽 | Settings |` ...totally made up.

I might argue this fake app _doesn't even need_ Navigation, as it's more or less a **single purpose app**. If we consider this route, I can see it as a nav-less UI -- in which case this is an opportunity to establish such a "Page Type" pattern. 

![image](https://user-images.githubusercontent.com/1165933/43843701-c32947ea-9aed-11e8-9fdd-54b472dcd9a3.png)

**Comment by arosenblum** [comment]
Good point on nav-less idea.  I guess the question is do we have a preference on what we want to demonstrate with this reference application?  Seems like ADC devs would need examples of both (somehow).
