### ISSUE TITLE
Determine Inspections fake "app name"

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ref-app-inspections#7]
Currently "FIC, Farm Inspection Console"

![image](https://user-images.githubusercontent.com/1165933/43837349-d9002012-9add-11e8-95d3-7e52879ac69c.png)

**Comment by francisrupert** [comment]
@atdiff, @arosenblum, @bignamehere,

Following the typical pattern here of `[abbr] [spelled-out-name]`, I randomly came up with `FIC, Farm Inspection Console`.

Feel free to use this comment space to rip that name apart, get behind it, or brainstorm some new ones. 

Here's the naming challenge: how clear should it be that it's _not_ a real FSA app, but still looks good (as opposed to [YAFANS](http://usda-fsa.github.io/fsa-style/boilerplate.html)).

Whatchathink?

![image](https://user-images.githubusercontent.com/1165933/43837349-d9002012-9add-11e8-95d3-7e52879ac69c.png)

**Comment by arosenblum** [comment]
Just a few ideas:

- SRA | SPA Reference Application
- FIRA | Farm Inspections Reference Application
- RAFI | Reference App for Farm Inspections

I guess part of it comes down to whether or not we feel we should include the words "Farm Inspection" or similar.  We socially refer to it as the SPA Reference Application when we talk to people (right or wrong).
